
INSERT INTO [SwiftFinancialsDB_DEV].[dbo].[swiftfin_AdministrativeDivisions]([Id]
	  ,[ParentId]
      ,[Description]
      ,[Depth]
      ,[Type]
      ,[Remarks]
      ,[IsLocked]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate])

SELECT TOP (1000) [Id]
      ,[ParentId]
      ,[Description]
      ,[Depth]
      ,[Type]
      ,[Remarks]
      ,[IsLocked]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate]
  FROM [SwiftFinancialsDB_TEST].[dbo].[vfin_AdministrativeDivisions]
