INSERT INTO [SwiftFinancialsDB_DEV].[dbo].[swiftfin_ChartOfAccounts]([Id]
,[ParentId]
      ,[CostCenterId]
      ,[AccountType]
      ,[AccountCategory]
      ,[AccountCode]
      ,[AccountName]
      ,[Depth]
      ,[IsControlAccount]
      ,[IsReconciliationAccount]
      ,[PostAutomaticallyOnly]
      ,[IsLocked]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate])


SELECT TOP (1000) [Id]
      ,[ParentId]
      ,[CostCenterId]
      ,[AccountType]
      ,[AccountCategory]
      ,[AccountCode]
      ,[AccountName]
      ,[Depth]
      ,[IsControlAccount]
      ,[IsReconciliationAccount]
      ,[PostAutomaticallyOnly]
      ,[IsLocked]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate]
  FROM [SwiftFinancialsDB_Test].[dbo].[vfin_ChartOfAccounts]
