INSERT INTO  [SwiftFinancialsDB_Live].[dbo].[swiftfin_Directors] ([Id]
  ,[DivisionId]
      ,[CustomerId]
      ,[Remarks]
      ,[IsLocked]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate])
SELECT TOP (1000) [Id]
      ,[DivisionId]
      ,[CustomerId]
      ,[Remarks]
      ,[IsLocked]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate]
  FROM [SwiftFinancialsDB_TEST].[dbo].[vfin_Directors]
