
INSERT INTO [SwiftFinancialsDB_Live].[dbo].[swiftfin_Employers]([Id]
	  ,[Description]
      ,[Address_AddressLine1]
      ,[Address_AddressLine2]
      ,[Address_Street]
      ,[Address_PostalCode]
      ,[Address_City]
      ,[Address_Email]
      ,[Address_LandLine]
      ,[Address_MobileLine]
      ,[RetirementAge]
      ,[EnforceRetirementAge]
      ,[IsLocked]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate])

SELECT TOP (1000) [Id]
      ,[Description]
      ,[Address_AddressLine1]
      ,[Address_AddressLine2]
      ,[Address_Street]
      ,[Address_PostalCode]
      ,[Address_City]
      ,[Address_Email]
      ,[Address_LandLine]
      ,[Address_MobileLine]
      ,[RetirementAge]
      ,[EnforceRetirementAge]
      ,[IsLocked]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate]
  FROM [SwiftFinancialsDB_TEST].[dbo].[vfin_Employers]
