
INSERT INTO [SwiftFinancialsDB_Live].[dbo].[swiftfin_JournalVouchers]([Id]
      ,[BranchId]
      ,[PostingPeriodId]
      ,[ChartOfAccountId]
      ,[CustomerAccountId]
      ,[Type]
      ,[VoucherNumber]
      ,[TotalValue]
      ,[PrimaryDescription]
      ,[SecondaryDescription]
      ,[Reference]
      ,[ValueDate]
      ,[Status]
      ,[AuditedBy]
      ,[AuditRemarks]
      ,[AuditedDate]
      ,[AuthorizedBy]
      ,[AuthorizationRemarks]
      ,[AuthorizedDate]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate])

SELECT [Id]
      ,[BranchId]
      ,[PostingPeriodId]
      ,[ChartOfAccountId]
      ,[CustomerAccountId]
      ,[Type]
      ,[VoucherNumber]
      ,[TotalValue]
      ,[PrimaryDescription]
      ,[SecondaryDescription]
      ,[Reference]
      ,[ValueDate]
      ,[Status]
      ,[AuditedBy]
      ,[AuditRemarks]
      ,[AuditedDate]
      ,[AuthorizedBy]
      ,[AuthorizationRemarks]
      ,[AuthorizedDate]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate]
  FROM [SwiftFinancialsDB_TEST].[dbo].[vfin_JournalVouchers]