INSERT INTO  [SwiftFinancialsDB_DEV].[dbo].[swiftfin_SalaryHeads] ([Id]
      ,[ChartOfAccountId]
      ,[Description]
      ,[Type]
      ,[Category]
      ,[IsOneOff]
      ,[CustomerAccountType_ProductCode]
      ,[CustomerAccountType_TargetProductId]
      ,[CustomerAccountType_TargetProductCode]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate])
SELECT TOP (1000) [Id]
      ,[ChartOfAccountId]
      ,[Description]
      ,[Type]
      ,[Category]
      ,[IsOneOff]
      ,[CustomerAccountType_ProductCode]
      ,[CustomerAccountType_TargetProductId]
      ,[CustomerAccountType_TargetProductCode]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate]
  FROM [SwiftFinancialsDB_TEST].[dbo].[vfin_SalaryHeads]
