
INSERT INTO [SwiftFinancialsDB_DEV].[dbo].[swiftfin_Stations]([Id]
      ,[ZoneId]
      ,[Description]
      ,[Address_AddressLine1]
      ,[Address_AddressLine2]
      ,[Address_Street]
      ,[Address_PostalCode]
      ,[Address_City]
      ,[Address_Email]
      ,[Address_LandLine]
      ,[Address_MobileLine]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate])
SELECT TOP (1000) [Id]
      ,[ZoneId]
      ,[Description]
      ,[Address_AddressLine1]
      ,[Address_AddressLine2]
      ,[Address_Street]
      ,[Address_PostalCode]
      ,[Address_City]
      ,[Address_Email]
      ,[Address_LandLine]
      ,[Address_MobileLine]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate]
  FROM [SwiftFinancialsDB_TEST].[dbo].[vfin_Stations]
