INSERT INTO [SwiftFinancialsDB_DEV].[dbo].[swiftfin_Branches]([Id]
      ,[CompanyId]
      ,[Code]
      ,[Description]
      ,[Address_AddressLine1]
      ,[Address_AddressLine2]
      ,[Address_Street]
      ,[Address_PostalCode]
      ,[Address_City]
      ,[Address_Email]
      ,[Address_LandLine]
      ,[Address_MobileLine]
      ,[IsLocked]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate])
   

SELECT  [Id]
      ,[CompanyId]
      ,[Code]
      ,[Description]
      ,[Address_AddressLine1]
      ,[Address_AddressLine2]
      ,[Address_Street]
      ,[Address_PostalCode]
      ,[Address_City]
      ,[Address_Email]
      ,[Address_LandLine]
      ,[Address_MobileLine]
      ,[IsLocked]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate]
  FROM [SwiftFinancialsDB_TEST].[dbo].[vfin_Branches]
