INSERT INTO [SwiftFinancialsDB_DEV].[dbo].[swiftfin_DebitTypeCommissions]([Id]
      ,[DebitTypeId]
      ,[CommissionId]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate])
SELECT TOP (1000) [Id]
      ,[DebitTypeId]
      ,[CommissionId]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate]
  FROM [SwiftFinancialsDB_Test].[dbo].[vfin_DebitTypeCommissions]
