INSERT INTO [SwiftFinancialsDB_DEV].[dbo].[swiftfin_DebitBatchEntries]([Id]
      ,[DebitBatchId]
      ,[CustomerAccountId]
      ,[Multiplier]
      ,[Reference]
      ,[Status]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate]
      ,[BasisValue])
SELECT TOP (1000) [Id]
      ,[DebitBatchId]
      ,[CustomerAccountId]
      ,[Multiplier]
      ,[Reference]
      ,[Status]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate]
      ,[BasisValue]
  FROM [SwiftFinancialsDB_Test].[dbo].[vfin_DebitBatchEntries]
