INSERT INTO [SwiftFinancialsDB_DEV].[dbo].[swiftfin_DebitTypes]([Id]
      ,[Description]
      ,[CustomerAccountType_ProductCode]
      ,[CustomerAccountType_TargetProductId]
      ,[CustomerAccountType_TargetProductCode]
      ,[IsLocked]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate])
SELECT TOP (1000) [Id]
      ,[Description]
      ,[CustomerAccountType_ProductCode]
      ,[CustomerAccountType_TargetProductId]
      ,[CustomerAccountType_TargetProductCode]
      ,[IsLocked]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate]
  FROM [SwiftFinancialsDB_Test].[dbo].[vfin_DebitTypes]
