

INSERT INTO [SwiftFinancialsDB_DEV].[dbo].[swiftfin_Journals]([Id]
 ,[ParentId]
      ,[PostingPeriodId]
      ,[BranchId]
      ,[AlternateChannelLogId]
      ,[TotalValue]
      ,[PrimaryDescription]
      ,[SecondaryDescription]
      ,[Reference]
      ,[ApplicationUserName]
      ,[EnvironmentUserName]
      ,[EnvironmentMachineName]
      ,[EnvironmentDomainName]
      ,[EnvironmentOSVersion]
      ,[EnvironmentMACAddress]
      ,[EnvironmentMotherboardSerialNumber]
      ,[EnvironmentProcessorId]
      ,[EnvironmentIPAddress]
      ,[ModuleNavigationItemCode]
      ,[TransactionCode]
      ,[ValueDate]
      ,[SuppressAccountAlert]
      ,[IsLocked]
      ,[IntegrityHash]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate]

)


SELECT TOP (1000) [Id]
      ,[ParentId]
      ,[PostingPeriodId]
      ,[BranchId]
      ,[AlternateChannelLogId]
      ,[TotalValue]
      ,[PrimaryDescription]
      ,[SecondaryDescription]
      ,[Reference]
      ,[ApplicationUserName]
      ,[EnvironmentUserName]
      ,[EnvironmentMachineName]
      ,[EnvironmentDomainName]
      ,[EnvironmentOSVersion]
      ,[EnvironmentMACAddress]
      ,[EnvironmentMotherboardSerialNumber]
      ,[EnvironmentProcessorId]
      ,[EnvironmentIPAddress]
      ,[ModuleNavigationItemCode]
      ,[TransactionCode]
      ,[ValueDate]
      ,[SuppressAccountAlert]
      ,[IsLocked]
      ,[IntegrityHash]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate]
  FROM [SwiftFinancialsDB_TEST].[dbo].[vfin_Journals]
