
/****** Script for SelectTopNRows command from SSMS  ******/
 INSERT INTO [SwiftFinancialsDB_DEV].[dbo].[swiftfin_SalaryCards]([Id]
      ,[EmployeeId]
      ,[SalaryGroupId]
      ,[CardNumber]
      ,[IsTaxExempt]
      ,[TaxExemption]
      ,[InsuranceReliefAmount]
      ,[Remarks]
      ,[IsLocked]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate])
 
SELECT [Id]
      ,[EmployeeId]
      ,[SalaryGroupId]
      ,[CardNumber]
      ,[IsTaxExempt]
      ,[TaxExemption]
      ,[InsuranceReliefAmount]
      ,[Remarks]
      ,[IsLocked]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate]
  FROM [SwiftFinancialsDB_TEST].[dbo].[vfin_SalaryCards]