INSERT INTO  [SwiftFinancialsDB_DEV].[dbo].[swiftfin_SalaryCardEntries] ([Id]
      ,[SalaryCardId]
      ,[SalaryGroupEntryId]
      ,[Charge_Type]
      ,[Charge_Percentage]
      ,[Charge_FixedAmount]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate])
SELECT [Id]
      ,[SalaryCardId]
      ,[SalaryGroupEntryId]
      ,[Charge_Type]
      ,[Charge_Percentage]
      ,[Charge_FixedAmount]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate]
  FROM [SwiftFinancialsDB_TEST].[dbo].[vfin_SalaryCardEntries]
