INSERT INTO  [SwiftFinancialsDB_DEV].[dbo].[swiftfin_StandingOrders]([Id]
      ,[BenefactorCustomerAccountId]
      ,[BeneficiaryCustomerAccountId]
      ,[Duration_StartDate]
      ,[Duration_EndDate]
      ,[Schedule_Frequency]
      ,[Schedule_ExpectedRunDate]
      ,[Schedule_ActualRunDate]
      ,[Schedule_ExecuteAttemptCount]
      ,[Schedule_ForceExecute]
      ,[Charge_Type]
      ,[Charge_Percentage]
      ,[Charge_FixedAmount]
      ,[Trigger]
      ,[LoanAmount]
      ,[PaymentPerPeriod]
      ,[Principal]
      ,[Interest]
      ,[CapitalizedInterest]
      ,[Remarks]
      ,[Chargeable]
      ,[IsLocked]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate])



SELECT TOP (1000) [Id]
      ,[BenefactorCustomerAccountId]
      ,[BeneficiaryCustomerAccountId]
      ,[Duration_StartDate]
      ,[Duration_EndDate]
      ,[Schedule_Frequency]
      ,[Schedule_ExpectedRunDate]
      ,[Schedule_ActualRunDate]
      ,[Schedule_ExecuteAttemptCount]
      ,[Schedule_ForceExecute]
      ,[Charge_Type]
      ,[Charge_Percentage]
      ,[Charge_FixedAmount]
      ,[Trigger]
      ,[LoanAmount]
      ,[PaymentPerPeriod]
      ,[Principal]
      ,[Interest]
      ,[CapitalizedInterest]
      ,[Remarks]
      ,[Chargeable]
      ,[IsLocked]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate]
  FROM [SwiftFinancialsDB_Test].[dbo].[vfin_StandingOrders]
