INSERT INTO  [SwiftFinancialsDB_DEV].[dbo].[swiftfin_Treasuries] ([Id]
      ,[BranchId]
      ,[ChartOfAccountId]
      ,[Code]
      ,[Description]
      ,[Range_LowerLimit]
      ,[Range_UpperLimit]
      ,[IsLocked]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate]
)
SELECT TOP (1000) [Id]
      ,[BranchId]
      ,[ChartOfAccountId]
      ,[Code]
      ,[Description]
      ,[Range_LowerLimit]
      ,[Range_UpperLimit]
      ,[IsLocked]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate]
  FROM [SwiftFinancialsDB_TEST].[dbo].[vfin_Treasuries]
