using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TestApis.Models
{
    public class UnitOfMeasure
    {
        public Guid Id { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Guid SequentialId { get; set; }   // auto-generated by DB
        public string CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
    }
}