/****** Script for SelectTopNRows command from SSMS  ******/
INSERT INTO [SwiftFinancialsDB_DEV].[dbo].[swiftfin_BudgetEntries]([Id]
      ,[BudgetId]
      ,[Type]
      ,[ChartOfAccountId]
      ,[Amount]
      ,[Reference]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate])
SELECT TOP (1000) [Id]
      ,[BudgetId]
      ,[Type]
      ,[ChartOfAccountId]
      ,[Amount]
      ,[Reference]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate]
  FROM [SwiftFinancialsDB_Test].[dbo].[vfin_BudgetEntries]