/****** Script for SelectTopNRows command from SSMS  ******/
INSERT INTO [SwiftFinancialsDB_DEV].[dbo].[swiftfin_Commissions]
SELECT TOP (1000) [Id]
      ,[Description]
      ,[MaximumCharge]
      ,[RoundingType]
      ,[IsLocked]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate]
  FROM [SwiftFinancialsDB_Test].[dbo].[vfin_Commissions]