


  INSERT INTO [SwiftFinancialsDB_DEV].[dbo].[swiftfin_CustomerAccounts] ([Id]
      ,[CustomerId]
      ,[BranchId]
      ,[CustomerAccountType_ProductCode]
      ,[CustomerAccountType_TargetProductId]
      ,[CustomerAccountType_TargetProductCode]
      ,[ScoredLoanDisbursementProductCode]
      ,[ScoredLoanLimit]
      ,[ScoredLoanLimitRemarks]
      ,[ScoredLoanLimitDate]
      ,[Status]
      ,[Remarks]
      ,[RecordStatus]
      ,[ModifiedBy]
      ,[ModifiedDate]
      ,[SigningInstructions]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate])
 
SELECT [Id]
      ,[CustomerId]
      ,[BranchId]
      ,[CustomerAccountType_ProductCode]
      ,[CustomerAccountType_TargetProductId]
      ,[CustomerAccountType_TargetProductCode]
      ,[ScoredLoanDisbursementProductCode]
      ,[ScoredLoanLimit]
      ,[ScoredLoanLimitRemarks]
      ,[ScoredLoanLimitDate]
      ,[Status]
      ,[Remarks]
      ,[RecordStatus]
      ,[ModifiedBy]
      ,[ModifiedDate]
      ,[SigningInstructions]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate]
  FROM [SwiftFinancialsDB_TEST].[dbo].[vfin_CustomerAccounts]