/****** Script for SelectTopNRows command from SSMS  ******/
INSERT INTO [SwiftFinancialsDB_DEV].[dbo].[swiftfin_DebitBatches]
SELECT TOP (1000) [Id]
      ,[DebitTypeId]
      ,[BranchId]
      ,[BatchNumber]
      ,[Reference]
      ,[Priority]
      ,[Status]
      ,[AuditedBy]
      ,[AuditRemarks]
      ,[AuditedDate]
      ,[AuthorizedBy]
      ,[AuthorizationRemarks]
      ,[AuthorizedDate]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate]
  FROM [SwiftFinancialsDB_Test].[dbo].[vfin_DebitBatches]