INSERT INTO [SwiftFinancialsDB_DEV].[dbo].[swiftfin_ExpensePayables] ([Id]

      ,[BranchId]
      ,[ChartOfAccountId]
      ,[VoucherNumber]
      ,[Type]
      ,[TotalValue]
      ,[ValueDate]
      ,[Remarks]
      ,[Status]
      ,[AuditedBy]
      ,[AuditRemarks]
      ,[AuditedDate]
      ,[AuthorizedBy]
      ,[AuthorizationRemarks]
      ,[AuthorizedDate]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate])


SELECT [Id]
      ,[BranchId]
      ,[ChartOfAccountId]
      ,[VoucherNumber]
      ,[Type]
      ,[TotalValue]
      ,[ValueDate]
      ,[Remarks]
      ,[Status]
      ,[AuditedBy]
      ,[AuditRemarks]
      ,[AuditedDate]
      ,[AuthorizedBy]
      ,[AuthorizationRemarks]
      ,[AuthorizedDate]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate]
  FROM [SwiftFinancialsDB_TEST].[dbo].[vfin_ExpensePayables]
