/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [Id]

      ,[BranchId]
      ,[ChartOfAccountId]
      ,[VoucherNumber]
      ,[Type]
      ,[TotalValue]
      ,[ValueDate]
      ,[Remarks]
      ,[Status]
      ,[AuditedBy]
      ,[AuditRemarks]
      ,[AuditedDate]
      ,[AuthorizedBy]
      ,[AuthorizationRemarks]
      ,[AuthorizedDate]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate]
  FROM [SwiftFinancialsDB_DEV].[dbo].[swiftfin_ExpensePayables]