/****** Script for SelectTopNRows command from SSMS  ******/
 INSERT INTO [SwiftFinancialsDB_DEV].[dbo].[swiftfin_JournalEntries] ([Id]
      ,[JournalId]
      ,[ChartOfAccountId]
      ,[ContraChartOfAccountId]
      ,[CustomerAccountId]
      ,[Amount]
      ,[ValueDate]
      ,[IntegrityHash]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate])
  
SELECT [Id]
      ,[JournalId]
      ,[ChartOfAccountId]
      ,[ContraChartOfAccountId]
      ,[CustomerAccountId]
      ,[Amount]
      ,[ValueDate]
      ,[IntegrityHash]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate]
  FROM [SwiftFinancialsDB_TEST].[dbo].[vfin_JournalEntries]