/****** Script for SelectTopNRows command from SSMS  ******/
INSERT INTO [SwiftFinancialsDB_DEV].[dbo].[swiftfin_LeaveTypes] ( [Id]
      ,[Description]
      ,[UnitType]
      ,[Entitlement]
      ,[TargetGender]
      ,[IsAccrued]
      ,[IsLocked]
      ,[ExcludeHolidays]
      ,[ExcludeWeekends]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate])
SELECT TOP (1000) [Id]
      ,[Description]
      ,[UnitType]
      ,[Entitlement]
      ,[TargetGender]
      ,[IsAccrued]
      ,[IsLocked]
      ,[ExcludeHolidays]
      ,[ExcludeWeekends]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate]
  FROM [SwiftFinancialsDB_TEST].[dbo].[vfin_LeaveTypes]
