/****** Script for SelectTopNRows command from SSMS  ******/
INSERT INTO [SwiftFinancialsDB_DEV].[dbo].[swiftfin_LoanGuarantors]([Id]
      ,[CustomerId]
      ,[LoaneeCustomerId]
      ,[LoanProductId]
      ,[LoanCaseId]
      ,[Status]
      ,[TotalShares]
      ,[CommittedShares]
      ,[AmountGuaranteed]
      ,[AmountPledged]
      ,[AppraisalFactor]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate])
SELECT [Id]
      ,[CustomerId]
      ,[LoaneeCustomerId]
      ,[LoanProductId]
      ,[LoanCaseId]
      ,[Status]
      ,[TotalShares]
      ,[CommittedShares]
      ,[AmountGuaranteed]
      ,[AmountPledged]
      ,[AppraisalFactor]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate]
  FROM [SwiftFinancialsDB_Test].[dbo].[vfin_LoanGuarantors]