
INSERT INTO   [SwiftFinancialsDB_DEV].[dbo].[swiftfin_Tellers]([Id]
      ,[Type]
      ,[EmployeeId]
      ,[ChartOfAccountId]
      ,[ShortageChartOfAccountId]
      ,[ExcessChartOfAccountId]
      ,[FloatCustomerAccountId]
      ,[CommissionCustomerAccountId]
      ,[Code]
      ,[Description]
      ,[Range_LowerLimit]
      ,[Range_UpperLimit]
      ,[MiniStatementItemsCap]
      ,[Reference]
      ,[IsLocked]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate])

SELECT [Id]
      ,[Type]
      ,[EmployeeId]
      ,[ChartOfAccountId]
      ,[ShortageChartOfAccountId]
      ,[ExcessChartOfAccountId]
      ,[FloatCustomerAccountId]
      ,[CommissionCustomerAccountId]
      ,[Code]
      ,[Description]
      ,[Range_LowerLimit]
      ,[Range_UpperLimit]
      ,[MiniStatementItemsCap]
      ,[Reference]
      ,[IsLocked]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate]
  FROM [SwiftFinancialsDB_TEST].[dbo].[vfin_Tellers]