INSERT INTO [SwiftFinancialsDB_DEV].[dbo].[swiftfin_TextAlerts] ([Id]
  ,[CompanyId]
  ,[TextMessage_Recipient]
  ,[TextMessage_Body]
  ,[TextMessage_DLRStatus]
  ,[TextMessage_Reference]
  ,[TextMessage_Origin]
  ,[TextMessage_Priority]
  ,[TextMessage_SendRetry]
  ,[TextMessage_SecurityCritical]
  ,[SequentialId]
  ,[CreatedBy]
  ,[CreatedDate])
SELECT [Id]
  ,(SELECT TOP 1 [Id] FROM [swiftfin_Companies]) AS [CompanyId] -- Replace [Company] with the actual table name containing company identifiers
  ,[TextMessage_Recipient]
  ,[TextMessage_Body]
  ,[TextMessage_DLRStatus]
  ,[TextMessage_Reference]
  ,[TextMessage_Origin]
  ,[TextMessage_Priority]
  ,[TextMessage_SendRetry]
  ,[TextMessage_SecurityCritical]
  ,[SequentialId]
  ,[CreatedBy]
  ,[CreatedDate]
FROM [SwiftFinancialsDB_TEST].[dbo].[vfin_TextAlerts];
