/****** Script for SelectTopNRows command from SSMS  ******/
INSERT INTO  [SwiftFinancialsDB_DEV].[dbo].[swiftfin_TrainingPeriods] ([Id]
      ,[Description]
      ,[Venue]
      ,[Duration_StartDate]
      ,[Duration_EndDate]
      ,[TotalValue]
      ,[DocumentNumber]
      ,[FileName]
      ,[FileTitle]
      ,[FileDescription]
      ,[FileMIMEType]
      ,[Remarks]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate]
)
SELECT TOP (1000) [Id]
      ,[Description]
      ,[Venue]
      ,[Duration_StartDate]
      ,[Duration_EndDate]
      ,[TotalValue]
      ,[DocumentNumber]
      ,[FileName]
      ,[FileTitle]
      ,[FileDescription]
      ,[FileMIMEType]
      ,[Remarks]
      ,[SequentialId]
      ,[CreatedBy]
      ,[CreatedDate]
  FROM [SwiftFinancialsDB_DEV].[dbo].[swiftfin_TrainingPeriods]